SELECT addOrder(0, 1, 'CASH', 'BUKIT TIMAH', 'WOODLANDS', 2);
SELECT addOrder(0, 2, 'CASH', 'CITY HALL', 'ANG MO KIO', NULL);
SELECT addOrder(0, 3, 'CREDIT CARD',  'BUONA VISTA', 'TANJONG PAGAR', NULL);
SELECT addOrder(5, 2, 'CREDIT CARD',  'BUGIS', 'OUTTA SPACE', NULL);
SELECT addOrder(5, 1, 'CASH',  'YISHUM', 'GEYLANG', NULL);
SELECT addOrder(0, 3, 'CREDIT CARD',  'BUONA VISTA', 'TANJONG PAGAR', NULL);
SELECT addOrder(5, 64, 'CREDIT CARD', 'Jurong East', 'City Hall', NULL);
SELECT addOrder(5, 83, 'CREDIT CARD', 'Chinese Garden', 'Chinese Garden', 5);
SELECT addOrder(5, 99, 'CREDIT CARD', 'Yishun', 'Bugis', 5);
SELECT addOrder(5, 84, 'CREDIT CARD', 'Toa Payoh', 'Toa Payoh', NULL);
SELECT addOrder(5, 71, 'CREDIT CARD', 'Yishun', 'Toa Payoh', NULL);
SELECT addOrder(5, 36, 'CASH', 'Toa Payoh', 'Chinese Garden', NULL);
SELECT addOrder(5, 20, 'CREDIT CARD', 'Tanjong Pagar', 'Bugis', NULL);
SELECT addOrder(5, 3, 'CREDIT CARD', 'City Hall', 'City Hall', NULL);
SELECT addOrder(5, 75, 'CASH', 'Jurong East', 'Toa Payoh', 8);
SELECT addOrder(5, 92, 'CASH', 'Chinese Garden', 'Bugis', 6);
SELECT addOrder(5, 57, 'CASH', 'Bugis', 'Chinese Garden', 3);
SELECT addOrder(5, 44, 'CASH', 'Chinese Garden', 'Jurong East', 10);
SELECT addOrder(5, 77, 'CREDIT CARD', 'Chinese Garden', 'Chinese Garden', 11);
SELECT addOrder(5, 31, 'CASH', 'Yishun', 'Bugis', 10);
SELECT addOrder(5, 42, 'CASH', 'Jurong East', 'Jurong East', 8);
SELECT addOrder(5, 66, 'CASH', 'Chinese Garden', 'Chinese Garden', 11);
SELECT addOrder(5, 72, 'CREDIT CARD', 'City Hall', 'City Hall', 7);
SELECT addOrder(5, 40, 'CREDIT CARD', 'Toa Payoh', 'Tanjong Pagar', NULL);
SELECT addOrder(5, 68, 'CREDIT CARD', 'City Hall', 'Yishun', 3);
SELECT addOrder(5, 83, 'CASH', 'Toa Payoh', 'Yishun', 10);
SELECT addOrder(5, 99, 'CREDIT CARD', 'Yishun', 'City Hall', 11);
SELECT addOrder(5, 44, 'CASH', 'Tanjong Pagar', 'Bugis', 6);
SELECT addOrder(5, 70, 'CASH', 'Toa Payoh', 'Yishun', 2);
SELECT addOrder(5, 43, 'CASH', 'Bugis', 'Jurong East', 12);
SELECT addOrder(5, 52, 'CASH', 'City Hall', 'Tanjong Pagar', 5);
SELECT addOrder(5, 73, 'CASH', 'Jurong East', 'Jurong East', null);
SELECT addOrder(5, 25, 'CREDIT CARD', 'City Hall', 'Yishun', null);
SELECT addOrder(5, 49, 'CREDIT CARD', 'Chinese Garden', 'Chinese Garden', 10);
SELECT addOrder(5, 79, 'CREDIT CARD', 'Bugis', 'Chinese Garden', 5);
SELECT addOrder(5, 70, 'CASH', 'Chinese Garden', 'Chinese Garden', null);
SELECT addOrder(5, 67, 'CREDIT CARD', 'Toa Payoh', 'Jurong East', 7);
SELECT addOrder(5, 60, 'CASH', 'Yishun', 'Tanjong Pagar', 2);
SELECT addOrder(5, 99, 'CREDIT CARD', 'City Hall', 'Toa Payoh', null);
SELECT addOrder(5, 36, 'CASH', 'City Hall', 'Tanjong Pagar', 10);
SELECT addOrder(5, 68, 'CASH', 'Toa Payoh', 'Jurong East', 14);
SELECT addOrder(5, 53, 'CREDIT CARD', 'Jurong East', 'Chinese Garden', 10);
SELECT addOrder(5, 85, 'CASH', 'Chinese Garden', 'Bugis', 8);
SELECT addOrder(5, 63, 'CREDIT CARD', 'Toa Payoh', 'Jurong East', 6);
SELECT addOrder(5, 22, 'CASH', 'Yishun', 'Bugis', 5);
SELECT addOrder(5, 83, 'CASH', 'Tanjong Pagar', 'City Hall', null);
SELECT addOrder(5, 19, 'CREDIT CARD', 'City Hall', 'Chinese Garden', null);
SELECT addOrder(5, 24, 'CREDIT CARD', 'Yishun', 'Toa Payoh', 11);
SELECT addOrder(5, 79, 'CASH', 'Toa Payoh', 'City Hall', 6);
SELECT addOrder(5, 8, 'CASH', 'Chinese Garden', 'City Hall', 10);
SELECT addOrder(5, 20, 'CASH', 'Yishun', 'Yishun', 11);
SELECT addOrder(5, 76, 'CREDIT CARD', 'Toa Payoh', 'Chinese Garden', null);
SELECT addOrder(5, 62, 'CREDIT CARD', 'Toa Payoh', 'Chinese Garden', 16);
SELECT addOrder(5, 8, 'CREDIT CARD', 'Toa Payoh', 'Yishun', 11);
SELECT addOrder(5, 1, 'CASH', 'Bugis', 'Toa Payoh', 11);
SELECT addOrder(5, 22, 'CASH', 'Yishun', 'Tanjong Pagar', 3);
SELECT addOrder(5, 88, 'CASH', 'Toa Payoh', 'City Hall', 17);
SELECT addOrder(5, 22, 'CREDIT CARD', 'Yishun', 'Yishun', 8);
SELECT addOrder(5, 69, 'CASH', 'Yishun', 'Yishun', 17);
SELECT addOrder(5, 19, 'CREDIT CARD', 'Chinese Garden', 'Jurong East', null);
SELECT addOrder(5, 39, 'CASH', 'Bugis', 'Chinese Garden', 16);
SELECT addOrder(5, 4, 'CREDIT CARD', 'Chinese Garden', 'Chinese Garden', null);
SELECT addOrder(5, 51, 'CREDIT CARD', 'Tanjong Pagar', 'Yishun', 6);
SELECT addOrder(5, 68, 'CREDIT CARD', 'Tanjong Pagar', 'Yishun', 10);
SELECT addOrder(5, 60, 'CREDIT CARD', 'Yishun', 'Bugis', 14);
SELECT addOrder(5, 11, 'CASH', 'Tanjong Pagar', 'Chinese Garden', 8);
SELECT addOrder(5, 51, 'CREDIT CARD', 'Tanjong Pagar', 'City Hall', 17);
SELECT addOrder(5, 91, 'CREDIT CARD', 'City Hall', 'Chinese Garden', 16);
SELECT addOrder(5, 74, 'CASH', 'City Hall', 'Bugis', null);
SELECT addOrder(5, 74, 'CASH', 'Toa Payoh', 'Chinese Garden', 5);
SELECT addOrder(5, 41, 'CASH', 'Yishun', 'Chinese Garden', null);
SELECT addOrder(5, 54, 'CASH', 'Chinese Garden', 'Bugis', 8);
SELECT addOrder(5, 59, 'CASH', 'Toa Payoh', 'Yishun', 16);
SELECT addOrder(5, 67, 'CASH', 'Toa Payoh', 'City Hall', null);
SELECT addOrder(5, 59, 'CREDIT CARD', 'Bugis', 'Yishun', NULL);
SELECT addOrder(5, 85, 'CASH', 'Bugis', 'Chinese Garden', null);
SELECT addOrder(5, 52, 'CREDIT CARD', 'Yishun', 'Tanjong Pagar', 16);
SELECT addOrder(5, 9, 'CREDIT CARD', 'Yishun', 'City Hall', 16);
SELECT addOrder(5, 8, 'CASH', 'City Hall', 'Toa Payoh', 8);
SELECT addOrder(5, 5, 'CASH', 'Chinese Garden', 'City Hall', 10);
SELECT addOrder(5, 8, 'CREDIT CARD', 'Bugis', 'City Hall', 10);
SELECT addOrder(5, 69, 'CREDIT CARD', 'Chinese Garden', 'Bugis', 6);
SELECT addOrder(5, 91, 'CREDIT CARD', 'City Hall', 'Yishun', null);
SELECT addOrder(5, 68, 'CREDIT CARD', 'Tanjong Pagar', 'Yishun', null);
SELECT addOrder(5, 26, 'CREDIT CARD', 'Tanjong Pagar', 'City Hall', null);
SELECT addOrder(5, 83, 'CASH', 'Chinese Garden', 'Toa Payoh', 16);
SELECT addOrder(5, 21, 'CASH', 'Tanjong Pagar', 'City Hall', 6);
SELECT addOrder(5, 48, 'CASH', 'City Hall', 'Tanjong Pagar', null);
SELECT addOrder(5, 61, 'CASH', 'Tanjong Pagar', 'Bugis', 11);
SELECT addOrder(5, 54, 'CREDIT CARD', 'Chinese Garden', 'Chinese Garden', 17);
SELECT addOrder(5, 86, 'CASH', 'Tanjong Pagar', 'Chinese Garden', 3);
SELECT addOrder(5, 22, 'CREDIT CARD', 'Jurong East', 'Yishun', 16);
SELECT addOrder(5, 52, 'CASH', 'City Hall', 'Bugis', 17);
SELECT addOrder(5, 82, 'CREDIT CARD', 'Toa Payoh', 'Chinese Garden', 6);
SELECT addOrder(5, 46, 'CREDIT CARD', 'Bugis', 'Tanjong Pagar', null);
SELECT addOrder(5, 23, 'CASH', 'Yishun', 'Chinese Garden', 17);
SELECT addOrder(5, 14, 'CASH', 'Yishun', 'Chinese Garden', 11);
SELECT addOrder(5, 71, 'CASH', 'Bugis', 'Bugis', 10);
SELECT addOrder(5, 73, 'CREDIT CARD', 'Toa Payoh', 'City Hall', null);
SELECT addOrder(5, 5, 'CASH', 'Jurong East', 'Chinese Garden', 5);
SELECT addOrder(5, 54, 'CASH', 'Toa Payoh', 'Tanjong Pagar', 10);
SELECT addOrder(5, 75, 'CREDIT CARD', 'Yishun', 'Tanjong Pagar', 17);
SELECT addOrder(5, 88, 'CASH', 'Tanjong Pagar', 'Chinese Garden', null);
SELECT addOrder(5, 27, 'CREDIT CARD', 'Jurong East', 'Tanjong Pagar', 17);
SELECT addOrder(5, 60, 'CREDIT CARD', 'Jurong East', 'Bugis', 7);
SELECT addOrder(5, 58, 'CASH', 'Yishun', 'City Hall', 16);
SELECT allocateRider(1, 1);
SELECT allocateRider(2, 2);
SELECT allocateRider(4, 3);
SELECT allocateRider(3, 4);
SELECT allocateRider(95, 1);
SELECT allocateRider(94, 2);
SELECT allocateRider(93, 3);
SELECT allocateRider(92, 4);
SELECT allocateRider(91, 5);
SELECT allocateRider(90, 6);
SELECT allocateRider(89, 7);
SELECT allocateRider(88, 8);
SELECT allocateRider(87, 9);
SELECT allocateRider(86, 10);
SELECT allocateRider(85, 11);
SELECT allocateRider(84, 12);
SELECT allocateRider(83, 13);
SELECT allocateRider(82, 14);
SELECT allocateRider(81, 15);
SELECT allocateRider(80, 16);
SELECT allocateRider(79, 17);
SELECT allocateRider(78, 18);
SELECT allocateRider(77, 19);
SELECT allocateRider(76, 20);
SELECT allocateRider(75, 21);
SELECT allocateRider(74, 22);
SELECT allocateRider(73, 23);
SELECT allocateRider(72, 24);
SELECT allocateRider(71, 25);
SELECT allocateRider(70, 26);
SELECT allocateRider(69, 27);
SELECT allocateRider(68, 28);
SELECT allocateRider(67, 29);
SELECT allocateRider(66, 30);
SELECT allocateRider(65, 31);
SELECT allocateRider(64, 32);
SELECT allocateRider(63, 33);
SELECT allocateRider(62, 34);
SELECT allocateRider(61, 35);
SELECT allocateRider(60, 36);
SELECT allocateRider(59, 37);
SELECT allocateRider(58, 38);
SELECT allocateRider(57, 39);
SELECT allocateRider(56, 40);
SELECT allocateRider(55, 41);
SELECT allocateRider(54, 42);
SELECT allocateRider(53, 43);
SELECT allocateRider(52, 44);
SELECT allocateRider(51, 45);
SELECT allocateRider(50, 46);
SELECT allocateRider(49, 47);
SELECT allocateRider(48, 48);
SELECT allocateRider(47, 49);
SELECT allocateRider(46, 50);
SELECT allocateRider(45, 51);
SELECT allocateRider(44, 52);
SELECT allocateRider(43, 53);
SELECT allocateRider(42, 54);
SELECT allocateRider(41, 55);
SELECT allocateRider(40, 56);
SELECT allocateRider(39, 57);
SELECT allocateRider(38, 58);
SELECT allocateRider(37, 59);
SELECT allocateRider(36, 60);
SELECT allocateRider(35, 61);
SELECT allocateRider(34, 62);
SELECT allocateRider(33, 63);
SELECT allocateRider(32, 64);
SELECT allocateRider(31, 65);
SELECT allocateRider(30, 66);
SELECT allocateRider(29, 67);
SELECT allocateRider(28, 68);
SELECT allocateRider(27, 69);
SELECT allocateRider(26, 70);
SELECT allocateRider(25, 71);
SELECT allocateRider(24, 72);
SELECT allocateRider(23, 73);
SELECT allocateRider(22, 74);
SELECT allocateRider(21, 75);
SELECT allocateRider(20, 76);
SELECT allocateRider(19, 77);
SELECT allocateRider(18, 78);
SELECT allocateRider(17, 79);
SELECT allocateRider(16, 80);
SELECT allocateRider(15, 81);
SELECT allocateRider(14, 82);
SELECT allocateRider(13, 83);
SELECT allocateRider(12, 84);
SELECT allocateRider(11, 85);
SELECT allocateRider(10, 86);
SELECT allocateRider(9, 87);
SELECT allocateRider(8, 88);
SELECT allocateRider(7, 89);
SELECT allocateRider(6, 90);
SELECT allocateRider(5, 91);
SELECT allocateRider(4, 92);
SELECT allocateRider(3, 93);
SELECT allocateRider(2, 94);
SELECT allocateRider(1, 95);

SELECT timestamp_departForRest(1);
SELECT timestamp_arriveAtRest(1);
SELECT timestamp_departForRest(2);
SELECT timestamp_arriveAtRest(2);
SELECT timestamp_departFromRest(2);
SELECT timestamp_orderDelivered(2);
SELECT timestamp_departForRest(3);
SELECT timestamp_departForRest(4);
SELECT timestamp_departForRest(5);
SELECT timestamp_departForRest(6);
SELECT timestamp_arriveAtRest(6);
SELECT timestamp_departFromRest(6);
SELECT timestamp_orderDelivered(6);
SELECT timestamp_departForRest(7);
SELECT timestamp_arriveAtRest(7);
SELECT timestamp_departFromRest(7);
SELECT timestamp_orderDelivered(7);
SELECT timestamp_departForRest(8);
SELECT timestamp_arriveAtRest(8);
SELECT timestamp_departFromRest(8);
SELECT timestamp_orderDelivered(8);
SELECT timestamp_departForRest(9);
SELECT timestamp_departForRest(10);
SELECT timestamp_arriveAtRest(10);
SELECT timestamp_departFromRest(10);
SELECT timestamp_orderDelivered(10);
SELECT timestamp_departForRest(11);
SELECT timestamp_arriveAtRest(11);
SELECT timestamp_departFromRest(11);
SELECT timestamp_orderDelivered(11);
SELECT timestamp_departForRest(12);
SELECT timestamp_arriveAtRest(12);
SELECT timestamp_departFromRest(12);
SELECT timestamp_orderDelivered(12);
SELECT timestamp_departForRest(13);
SELECT timestamp_arriveAtRest(13);
SELECT timestamp_departForRest(14);
SELECT timestamp_arriveAtRest(14);
SELECT timestamp_departForRest(15);
SELECT timestamp_arriveAtRest(15);
SELECT timestamp_departFromRest(15);
SELECT timestamp_orderDelivered(15);
SELECT timestamp_departForRest(16);
SELECT timestamp_departForRest(17);
SELECT timestamp_arriveAtRest(17);
SELECT timestamp_departFromRest(17);
SELECT timestamp_orderDelivered(17);
SELECT timestamp_departForRest(18);
SELECT timestamp_arriveAtRest(18);
SELECT timestamp_departForRest(19);
SELECT timestamp_departForRest(20);
SELECT timestamp_arriveAtRest(20);
SELECT timestamp_departFromRest(20);
SELECT timestamp_orderDelivered(20);
SELECT timestamp_departForRest(21);
SELECT timestamp_departForRest(22);
SELECT timestamp_arriveAtRest(22);
SELECT timestamp_departForRest(23);
SELECT timestamp_arriveAtRest(23);
SELECT timestamp_departFromRest(23);
SELECT timestamp_orderDelivered(23);
SELECT timestamp_departForRest(24);
SELECT timestamp_arriveAtRest(24);
SELECT timestamp_departFromRest(24);
SELECT timestamp_orderDelivered(24);
SELECT timestamp_departForRest(25);
SELECT timestamp_arriveAtRest(25);
SELECT timestamp_departForRest(26);
SELECT timestamp_arriveAtRest(26);
SELECT timestamp_departFromRest(26);
SELECT timestamp_orderDelivered(26);
SELECT timestamp_departForRest(27);
SELECT timestamp_departForRest(28);
SELECT timestamp_arriveAtRest(28);
SELECT timestamp_departFromRest(28);
SELECT timestamp_orderDelivered(28);
SELECT timestamp_departForRest(29);
SELECT timestamp_arriveAtRest(29);
SELECT timestamp_departFromRest(29);
SELECT timestamp_departForRest(30);
SELECT timestamp_arriveAtRest(30);
SELECT timestamp_departFromRest(30);
SELECT timestamp_departForRest(31);
SELECT timestamp_arriveAtRest(31);
SELECT timestamp_departFromRest(31);
SELECT timestamp_orderDelivered(31);
SELECT timestamp_departForRest(32);
SELECT timestamp_departForRest(33);
SELECT timestamp_arriveAtRest(33);
SELECT timestamp_departFromRest(33);
SELECT timestamp_orderDelivered(33);
SELECT timestamp_departForRest(34);
SELECT timestamp_arriveAtRest(34);
SELECT timestamp_departForRest(35);
SELECT timestamp_arriveAtRest(35);
SELECT timestamp_departFromRest(35);
SELECT timestamp_orderDelivered(35);
SELECT timestamp_departForRest(36);
SELECT timestamp_arriveAtRest(36);
SELECT timestamp_departForRest(37);
SELECT timestamp_arriveAtRest(37);
SELECT timestamp_departFromRest(37);
SELECT timestamp_orderDelivered(37);
SELECT timestamp_departForRest(38);
SELECT timestamp_arriveAtRest(38);
SELECT timestamp_departFromRest(38);
SELECT timestamp_orderDelivered(38);
SELECT timestamp_departForRest(39);
SELECT timestamp_arriveAtRest(39);
SELECT timestamp_departForRest(40);
SELECT timestamp_arriveAtRest(40);
SELECT timestamp_departFromRest(40);
SELECT timestamp_departForRest(41);
SELECT timestamp_departForRest(42);
SELECT timestamp_arriveAtRest(42);
SELECT timestamp_departFromRest(42);
SELECT timestamp_departForRest(43);
SELECT timestamp_departForRest(44);
SELECT timestamp_departForRest(45);
SELECT timestamp_arriveAtRest(45);
SELECT timestamp_departForRest(46);
SELECT timestamp_departForRest(47);
SELECT timestamp_arriveAtRest(47);
SELECT timestamp_departFromRest(47);
SELECT timestamp_orderDelivered(47);
SELECT timestamp_departForRest(48);
SELECT timestamp_arriveAtRest(48);
SELECT timestamp_departFromRest(48);
SELECT timestamp_orderDelivered(48);
SELECT timestamp_departForRest(49);
SELECT timestamp_arriveAtRest(49);
SELECT timestamp_departFromRest(49);
SELECT timestamp_orderDelivered(49);
SELECT timestamp_departForRest(50);
SELECT timestamp_arriveAtRest(50);
SELECT timestamp_departFromRest(50);
SELECT timestamp_orderDelivered(50);
SELECT timestamp_departForRest(51);
SELECT timestamp_departForRest(52);
SELECT timestamp_departForRest(53);
SELECT timestamp_arriveAtRest(53);
SELECT timestamp_departForRest(54);
SELECT timestamp_departForRest(55);
SELECT timestamp_departForRest(56);
SELECT timestamp_arriveAtRest(56);
SELECT timestamp_departFromRest(56);
SELECT timestamp_departForRest(57);
SELECT timestamp_arriveAtRest(57);
SELECT timestamp_departFromRest(57);
SELECT timestamp_orderDelivered(57);
SELECT timestamp_departForRest(58);
SELECT timestamp_arriveAtRest(58);
SELECT timestamp_departForRest(59);
SELECT timestamp_arriveAtRest(59);
SELECT timestamp_departFromRest(59);
SELECT timestamp_orderDelivered(59);
SELECT timestamp_departForRest(60);
SELECT timestamp_arriveAtRest(60);
SELECT timestamp_departFromRest(60);
SELECT timestamp_departForRest(61);
SELECT timestamp_arriveAtRest(61);
SELECT timestamp_departForRest(62);
SELECT timestamp_arriveAtRest(62);
SELECT timestamp_departFromRest(62);
SELECT timestamp_orderDelivered(62);
SELECT timestamp_departForRest(63);
SELECT timestamp_arriveAtRest(63);
SELECT timestamp_departFromRest(63);
SELECT timestamp_orderDelivered(63);
SELECT timestamp_departForRest(64);
SELECT timestamp_departForRest(65);
SELECT timestamp_departForRest(66);
SELECT timestamp_arriveAtRest(66);
SELECT timestamp_departFromRest(66);
SELECT timestamp_orderDelivered(66);
SELECT timestamp_departForRest(67);
SELECT timestamp_arriveAtRest(67);
SELECT timestamp_departFromRest(67);
SELECT timestamp_orderDelivered(67);
SELECT timestamp_departForRest(68);
SELECT timestamp_arriveAtRest(68);
SELECT timestamp_departFromRest(68);
SELECT timestamp_departForRest(69);
SELECT timestamp_arriveAtRest(69);
SELECT timestamp_departFromRest(69);
SELECT timestamp_orderDelivered(69);
SELECT timestamp_departForRest(70);
SELECT timestamp_arriveAtRest(70);
SELECT timestamp_departFromRest(70);
SELECT timestamp_departForRest(71);
SELECT timestamp_departForRest(72);
SELECT timestamp_arriveAtRest(72);
SELECT timestamp_departFromRest(72);
SELECT timestamp_orderDelivered(72);
SELECT timestamp_departForRest(73);
SELECT timestamp_departForRest(74);
SELECT timestamp_arriveAtRest(74);
SELECT timestamp_departForRest(75);
SELECT timestamp_arriveAtRest(75);
SELECT timestamp_departFromRest(75);
SELECT timestamp_departForRest(76);
SELECT timestamp_arriveAtRest(76);
SELECT timestamp_departFromRest(76);
SELECT timestamp_orderDelivered(76);
SELECT timestamp_departForRest(77);
SELECT timestamp_arriveAtRest(77);
SELECT timestamp_departFromRest(77);
SELECT timestamp_departForRest(78);
SELECT timestamp_arriveAtRest(78);
SELECT timestamp_departForRest(79);
SELECT timestamp_departForRest(80);
SELECT timestamp_departForRest(81);
SELECT timestamp_departForRest(82);
SELECT timestamp_arriveAtRest(82);
SELECT timestamp_departForRest(83);
SELECT timestamp_departForRest(84);
SELECT timestamp_arriveAtRest(84);
SELECT timestamp_departFromRest(84);
SELECT timestamp_departForRest(85);
SELECT timestamp_arriveAtRest(85);
SELECT timestamp_departFromRest(85);
SELECT timestamp_orderDelivered(85);
SELECT timestamp_departForRest(86);
SELECT timestamp_arriveAtRest(86);
SELECT timestamp_departFromRest(86);
SELECT timestamp_departForRest(87);
SELECT timestamp_arriveAtRest(87);
SELECT timestamp_departFromRest(87);
SELECT timestamp_orderDelivered(87);
SELECT timestamp_departForRest(88);
SELECT timestamp_arriveAtRest(88);
SELECT timestamp_departFromRest(88);
SELECT timestamp_departForRest(89);
SELECT timestamp_arriveAtRest(89);
SELECT timestamp_departFromRest(89);