INSERT INTO Restaurants
values 
(DEFAULT, 'McDonalds', 'McDonalds Fastfood restaurant', DEFAULT, 'Western', 'Bukit Timah'),
(DEFAULT, 'Nana Thai', 'Cheap and Affordable Thai Food!', DEFAULT, 'Thai', 'City Hall'),
(DEFAULT, 'Pepperoni', 'Best pizza in town!', DEFAULT, 'Italian', 'Raffles Place'),
(DEFAULT, 'Makan Express', 'Makan all the way!', DEFAULT, 'Indian', 'Buona Vista'),
(DEFAULT, 'KFC', 'Fingers lickin good!', DEFAULT, 'Western', 'Tampines'),
(DEFAULT, 'McDonalds0', 'Big Food0', 20, 'Western' ,'Tanjong Pagar0'),
(DEFAULT, 'Hooters1', 'Big Food1', 25, 'Thai' ,'Tanjong Pagar1'),
(DEFAULT, 'Haw par villa2', 'Loving It!', 17, 'Mala' ,'Bugis2'),
(DEFAULT, 'Futurama3', 'Big Food3', 10, 'Fusion' ,'Chinese Garden3'),
(DEFAULT, 'Brooklyn 994', 'Cool, cool cool cool4', 15, 'Indian' ,'Jurong East4'),
(DEFAULT, 'Brooklyn 995', 'Space Future5', 25, 'Vegetarian' ,'Chinese Garden5'),
(DEFAULT, 'Haw par villa6', 'Big Food6', 15, 'Asian' ,'Yishun6'),
(DEFAULT, 'KFC7', 'Big Food7', 17, 'Thai' ,'Jurong East7'),
(DEFAULT, 'Hooters8', 'Big Food8', 15, 'Hotpot' ,'Jurong East8'),
(DEFAULT, 'Kopitiam9', 'Space Future9', 8, 'Snacks' ,'Yishun9'),
(DEFAULT, 'Brooklyn 9910', 'Big Food10', 8, 'Western' ,'Yishun10'),
(DEFAULT, 'McDonalds11', 'Space Future11', 8, 'Italian' ,'Bugis11'),
(DEFAULT, 'Futurama12', 'Cool, cool cool cool12', 25, 'Hotpot' ,'Toa Payoh12'),
(DEFAULT, 'Kopitiam13', 'Loving It!13', 15, 'Thai' ,'City Hall13'),
(DEFAULT, 'McDonalds14', 'Loving It!14', 15, 'Thai' ,'Toa Payoh14'),
(DEFAULT, 'McDonalds15', 'Finger Licking Good15', 10, 'Vegetarian' ,'Bugis15'),
(DEFAULT, 'Futurama16', 'Everything u want16', 8, 'Muslim' ,'Yishun16'),
(DEFAULT, 'Kopitiam17', 'Loving It!17', 15, 'Muslim' ,'Chinese Garden17'),
(DEFAULT, 'McDonalds18', 'Easy Breezy18', 20, 'Asian' ,'City Hall18'),
(DEFAULT, 'Kopitiam19', 'Cool, cool cool cool19', 25, 'Thai' ,'Tanjong Pagar19'),
(DEFAULT, 'McDonalds20', 'Big Food20', 10, 'Hotpot' ,'Chinese Garden20'),
(DEFAULT, 'McDonalds21', 'Cool, cool cool cool21', 15, 'Vegetarian' ,'Bugis21'),
(DEFAULT, 'Haw par villa22', 'Cool, cool cool cool22', 15, 'Thai' ,'City Hall22'),
(DEFAULT, 'McDonalds23', 'Space Future23', 25, 'Western' ,'City Hall23'),
(DEFAULT, 'Futurama24', 'Space Future24', 15, 'Fusion' ,'Chinese Garden24'),
(DEFAULT, 'Kopitiam25', 'Finger Licking Good25', 12, 'Mala' ,'Jurong East25'),
(DEFAULT, 'Hooters26', 'Easy Breezy26', 20, 'Indian' ,'Tanjong Pagar26'),
(DEFAULT, 'Kopitiam27', 'Cool, cool cool cool27', 8, 'Italian' ,'City Hall27'),
(DEFAULT, 'McDonalds28', 'Space Future28', 25, 'Fusion' ,'City Hall28'),
(DEFAULT, 'Haw par villa29', 'Everything u want29', 10, 'Indian' ,'Tanjong Pagar29');