SELECT addRider('caesar1', 'pw12345', 'Caesar 1', true, 'AVAILABLE');
SELECT addRider('caesar2', 'pw12345', 'Caesar 2', true, 'AVAILABLE');
SELECT addRider('caesar3', 'pw12345', 'Caesar 3', false);
SELECT addRider('caesar4', 'pw12345', 'Caesar 4', false, 'AVAILABLE');
SELECT addRider('caesar5', 'pw12345', 'Caesar 5', false);
SELECT addRider('harleyboi0', 'leatherman0', 'davidson guyz0', false, 'AVAILABLE');
SELECT addRider('harleyboi1', 'leatherman1', 'davidson guyz1', false, 'AVAILABLE');
SELECT addRider('harleyboi2', 'leatherman2', 'davidson guyz2', true, 'DELIVERING');
SELECT addRider('harleyboi3', 'leatherman3', 'davidson guyz3', false, 'DELIVERING');
SELECT addRider('harleyboi4', 'leatherman4', 'davidson guyz4', false, 'AVAILABLE');
SELECT addRider('harleyboi5', 'leatherman5', 'davidson guyz5', true, 'DELIVERING');
SELECT addRider('harleyboi6', 'leatherman6', 'davidson guyz6', true, 'AVAILABLE');
SELECT addRider('harleyboi7', 'leatherman7', 'davidson guyz7', false, 'NOT WORKING');
SELECT addRider('harleyboi8', 'leatherman8', 'davidson guyz8', false, 'DELIVERING');
SELECT addRider('harleyboi9', 'leatherman9', 'davidson guyz9', false, 'AVAILABLE');
SELECT addRider('harleyboi10', 'leatherman10', 'davidson guyz10', true, 'AVAILABLE');
SELECT addRider('harleyboi11', 'leatherman11', 'davidson guyz11', false, 'NOT WORKING');
SELECT addRider('harleyboi12', 'leatherman12', 'davidson guyz12', true, 'DELIVERING');
SELECT addRider('harleyboi13', 'leatherman13', 'davidson guyz13', true, 'NOT WORKING');
SELECT addRider('harleyboi14', 'leatherman14', 'davidson guyz14', true, 'NOT WORKING');
SELECT addRider('harleyboi15', 'leatherman15', 'davidson guyz15', true, 'DELIVERING');
SELECT addRider('harleyboi16', 'leatherman16', 'davidson guyz16', true, 'AVAILABLE');
SELECT addRider('harleyboi17', 'leatherman17', 'davidson guyz17', false, 'AVAILABLE');
SELECT addRider('harleyboi18', 'leatherman18', 'davidson guyz18', false, 'DELIVERING');
SELECT addRider('harleyboi19', 'leatherman19', 'davidson guyz19', false, 'DELIVERING');
SELECT addRider('harleyboi20', 'leatherman20', 'davidson guyz20', true, 'DELIVERING');
SELECT addRider('harleyboi21', 'leatherman21', 'davidson guyz21', false, 'DELIVERING');
SELECT addRider('harleyboi22', 'leatherman22', 'davidson guyz22', false, 'NOT WORKING');
SELECT addRider('harleyboi23', 'leatherman23', 'davidson guyz23', false, 'NOT WORKING');
SELECT addRider('harleyboi24', 'leatherman24', 'davidson guyz24', true, 'NOT WORKING');
SELECT addRider('harleyboi25', 'leatherman25', 'davidson guyz25', false, 'NOT WORKING');
SELECT addRider('harleyboi26', 'leatherman26', 'davidson guyz26', false, 'AVAILABLE');
SELECT addRider('harleyboi27', 'leatherman27', 'davidson guyz27', false, 'NOT WORKING');
SELECT addRider('harleyboi28', 'leatherman28', 'davidson guyz28', false, 'DELIVERING');
SELECT addRider('harleyboi29', 'leatherman29', 'davidson guyz29', false, 'NOT WORKING');
SELECT addRider('harleyboi30', 'leatherman30', 'davidson guyz30', false, 'AVAILABLE');
SELECT addRider('harleyboi31', 'leatherman31', 'davidson guyz31', false, 'AVAILABLE');
SELECT addRider('harleyboi32', 'leatherman32', 'davidson guyz32', true, 'DELIVERING');
SELECT addRider('harleyboi33', 'leatherman33', 'davidson guyz33', false, 'AVAILABLE');
SELECT addRider('harleyboi34', 'leatherman34', 'davidson guyz34', false, 'AVAILABLE');
SELECT addRider('harleyboi35', 'leatherman35', 'davidson guyz35', false, 'NOT WORKING');
SELECT addRider('harleyboi36', 'leatherman36', 'davidson guyz36', false, 'NOT WORKING');
SELECT addRider('harleyboi37', 'leatherman37', 'davidson guyz37', true, 'NOT WORKING');
SELECT addRider('harleyboi38', 'leatherman38', 'davidson guyz38', true, 'DELIVERING');
SELECT addRider('harleyboi39', 'leatherman39', 'davidson guyz39', false, 'AVAILABLE');
SELECT addRider('harleyboi40', 'leatherman40', 'davidson guyz40', true, 'NOT WORKING');
SELECT addRider('harleyboi41', 'leatherman41', 'davidson guyz41', false, 'DELIVERING');
SELECT addRider('harleyboi42', 'leatherman42', 'davidson guyz42', false, 'AVAILABLE');
SELECT addRider('harleyboi43', 'leatherman43', 'davidson guyz43', true, 'DELIVERING');
SELECT addRider('harleyboi44', 'leatherman44', 'davidson guyz44', true, 'AVAILABLE');
SELECT addRider('harleyboi45', 'leatherman45', 'davidson guyz45', false, 'AVAILABLE');
SELECT addRider('harleyboi46', 'leatherman46', 'davidson guyz46', false, 'DELIVERING');
SELECT addRider('harleyboi47', 'leatherman47', 'davidson guyz47', true, 'NOT WORKING');
SELECT addRider('harleyboi48', 'leatherman48', 'davidson guyz48', true, 'DELIVERING');
SELECT addRider('harleyboi49', 'leatherman49', 'davidson guyz49', false, 'AVAILABLE');
SELECT addRider('harleyboi50', 'leatherman50', 'davidson guyz50', true, 'AVAILABLE');
SELECT addRider('harleyboi51', 'leatherman51', 'davidson guyz51', true, 'AVAILABLE');
SELECT addRider('harleyboi52', 'leatherman52', 'davidson guyz52', false, 'NOT WORKING');
SELECT addRider('harleyboi53', 'leatherman53', 'davidson guyz53', true, 'DELIVERING');
SELECT addRider('harleyboi54', 'leatherman54', 'davidson guyz54', true, 'AVAILABLE');
SELECT addRider('harleyboi55', 'leatherman55', 'davidson guyz55', false, 'NOT WORKING');
SELECT addRider('harleyboi56', 'leatherman56', 'davidson guyz56', false, 'DELIVERING');
SELECT addRider('harleyboi57', 'leatherman57', 'davidson guyz57', false, 'AVAILABLE');
SELECT addRider('harleyboi58', 'leatherman58', 'davidson guyz58', false, 'DELIVERING');
SELECT addRider('harleyboi59', 'leatherman59', 'davidson guyz59', false, 'NOT WORKING');
SELECT addRider('harleyboi60', 'leatherman60', 'davidson guyz60', false, 'NOT WORKING');
SELECT addRider('harleyboi61', 'leatherman61', 'davidson guyz61', true, 'AVAILABLE');
SELECT addRider('harleyboi62', 'leatherman62', 'davidson guyz62', true, 'AVAILABLE');
SELECT addRider('harleyboi63', 'leatherman63', 'davidson guyz63', false, 'NOT WORKING');
SELECT addRider('harleyboi64', 'leatherman64', 'davidson guyz64', false, 'AVAILABLE');
SELECT addRider('harleyboi65', 'leatherman65', 'davidson guyz65', false, 'DELIVERING');
SELECT addRider('harleyboi66', 'leatherman66', 'davidson guyz66', false, 'NOT WORKING');
SELECT addRider('harleyboi67', 'leatherman67', 'davidson guyz67', true, 'NOT WORKING');
SELECT addRider('harleyboi68', 'leatherman68', 'davidson guyz68', false, 'NOT WORKING');
SELECT addRider('harleyboi69', 'leatherman69', 'davidson guyz69', false, 'AVAILABLE');
SELECT addRider('harleyboi70', 'leatherman70', 'davidson guyz70', true, 'AVAILABLE');
SELECT addRider('harleyboi71', 'leatherman71', 'davidson guyz71', true, 'NOT WORKING');
SELECT addRider('harleyboi72', 'leatherman72', 'davidson guyz72', false, 'AVAILABLE');
SELECT addRider('harleyboi73', 'leatherman73', 'davidson guyz73', true, 'AVAILABLE');
SELECT addRider('harleyboi74', 'leatherman74', 'davidson guyz74', false, 'DELIVERING');
SELECT addRider('harleyboi75', 'leatherman75', 'davidson guyz75', true, 'DELIVERING');
SELECT addRider('harleyboi76', 'leatherman76', 'davidson guyz76', false, 'NOT WORKING');
SELECT addRider('harleyboi77', 'leatherman77', 'davidson guyz77', false, 'NOT WORKING');
SELECT addRider('harleyboi78', 'leatherman78', 'davidson guyz78', false, 'NOT WORKING');
SELECT addRider('harleyboi79', 'leatherman79', 'davidson guyz79', false, 'DELIVERING');
SELECT addRider('harleyboi80', 'leatherman80', 'davidson guyz80', true, 'NOT WORKING');
SELECT addRider('harleyboi81', 'leatherman81', 'davidson guyz81', true, 'DELIVERING');
SELECT addRider('harleyboi82', 'leatherman82', 'davidson guyz82', false, 'AVAILABLE');
SELECT addRider('harleyboi83', 'leatherman83', 'davidson guyz83', true, 'DELIVERING');
SELECT addRider('harleyboi84', 'leatherman84', 'davidson guyz84', true, 'DELIVERING');
SELECT addRider('harleyboi85', 'leatherman85', 'davidson guyz85', true, 'DELIVERING');
SELECT addRider('harleyboi86', 'leatherman86', 'davidson guyz86', false, 'DELIVERING');
SELECT addRider('harleyboi87', 'leatherman87', 'davidson guyz87', true, 'AVAILABLE');
SELECT addRider('harleyboi88', 'leatherman88', 'davidson guyz88', true, 'DELIVERING');
SELECT addRider('harleyboi89', 'leatherman89', 'davidson guyz89', true, 'DELIVERING');
SELECT addRider('harleyboi90', 'leatherman90', 'davidson guyz90', true, 'AVAILABLE');
SELECT addRider('harleyboi91', 'leatherman91', 'davidson guyz91', true, 'DELIVERING');
SELECT addRider('harleyboi92', 'leatherman92', 'davidson guyz92', false, 'AVAILABLE');
SELECT addRider('harleyboi93', 'leatherman93', 'davidson guyz93', false, 'DELIVERING');
SELECT addRider('harleyboi94', 'leatherman94', 'davidson guyz94', true, 'DELIVERING');