DROP TYPE rights CASCADE;
DROP TYPE order_statuses CASCADE;
DROP TYPE methods CASCADE;
DROP TYPE rider_statuses CASCADE;

DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Restaurant_Categories CASCADE;
DROP TABLE IF EXISTS FDS_Managers CASCADE;
DROP TABLE IF EXISTS Promotions CASCADE;
DROP TABLE IF EXISTS Customers CASCADE;
DROP TABLE IF EXISTS Riders CASCADE;
DROP TABLE IF EXISTS Deliveries CASCADE;
DROP TABLE IF EXISTS Restaurants CASCADE;
DROP TABLE IF EXISTS Menus CASCADE;
DROP TABLE IF EXISTS Restaurant_Staff CASCADE;
DROP TABLE IF EXISTS Food_Items CASCADE;
DROP TABLE IF EXISTS Reports CASCADE;
DROP TABLE IF EXISTS Managers_Has_Promotions CASCADE;
DROP TABLE IF EXISTS Restaurants_Has_Promotions CASCADE;
DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS Order_Contains_Food CASCADE;
DROP TABLE IF EXISTS Customer_Rates_Delivery CASCADE;
DROP TABLE IF EXISTS Shifts CASCADE;

DROP FUNCTION IF EXISTS addUser(VARCHAR, VARCHAR, VARCHAR, RIGHTS);
DROP FUNCTION IF EXISTS addFdsManager(VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS addCustomer(VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS addRider(VARCHAR, VARCHAR, VARCHAR, BOOLEAN, RIDER_STATUSES);
DROP FUNCTION IF EXISTS authUser(VARCHAR, VARCHAR);

DROP FUNCTION IF EXISTS addRestaurant(VARCHAR, TEXT, INTEGER, VARCHAR);
DROP FUNCTION IF EXISTS addRestaurantStaff(VARCHAR, VARCHAR, VARCHAR, INTEGER);

DROP FUNCTION IF EXISTS getRestaurants();
DROP FUNCTION IF EXISTS getMenus(VARCHAR);
DROP FUNCTION IF EXISTS getFoodItems(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS addMenu(INTEGER, VARCHAR);
DROP FUNCTION IF EXISTS addFoodItem(INTEGER, INTEGER, VARCHAR, FLOAT, INTEGER);
DROP FUNCTION IF EXISTS addFoodToOrder(INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS addDelivery(FLOAT);
DROP FUNCTION IF EXISTS addOrder(FLOAT, INTEGER, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS getOrderStatus(INTEGER);
DROP FUNCTION IF EXISTS getCustomerProfile(INTEGER);
DROP FUNCTION IF EXISTS updateCC(INTEGER, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS getDeliveringOrder(INTEGER);
DROP FUNCTION IF EXISTS allocateRider(INTEGER, INTEGER);
DROP FUNCTION IF EXISTS getAvailableRiders();
DROP FUNCTION IF EXISTS timestamp_departForRest(did INTEGER);
DROP FUNCTION IF EXISTS timestamp_arriveAtRest(did INTEGER);
DROP FUNCTION IF EXISTS timestamp_departFromRest(did INTEGER);
DROP FUNCTION IF EXISTS timestamp_orderDelivered(did INTEGER);
DROP FUNCTION IF EXISTS getRatings(INTEGER);
-- DROP FUNCTION IF EXISTS 